name:                trace-tool
version:             0.1.0.0
github:              "githubuser/trace-tool"
license:             BSD-3-Clause
author:              "Filip Stevanovic"
maintainer:          "steva@kth.se"
copyright:           "2025 Filip Stevanovic"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trace-tool#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.5 && < 9.6
# - diagnose >= 2.5.1 && < 2.6
- prettyprinter >= 1.7.1 && < 1.8
- text >= 2.0 && < 2.2
- parser-combinators
- hasmtlib >= 2.8 && < 2.9
- containers
- prettyprinter-ansi-terminal
- optparse-applicative
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  trace-tool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trace-tool

tests:
  trace-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trace-tool
